// Auto-generated from zone1970.tab + common city names.
// Map of lowercase city/zone alias -> IANA zone. Used by search.
export const CITY_ALIASES: Record<string, string> = {
  "nyc": "America/New_York",
  "newyork": "America/New_York",
  "new york": "America/New_York",
  "la": "America/Los_Angeles",
  "london": "Europe/London",
  "tokyo": "Asia/Tokyo",
  "delhi": "Asia/Kolkata",
  "kolkata": "Asia/Kolkata",
  "calcutta": "Asia/Kolkata",
  "paris": "Europe/Paris",
  "berlin": "Europe/Berlin",
  "madrid": "Europe/Madrid",
  "rome": "Europe/Rome",
  "amsterdam": "Europe/Amsterdam",
  "vienna": "Europe/Vienna",
  "prague": "Europe/Prague",
  "moscow": "Europe/Moscow",
  "dubai": "Asia/Dubai",
  "singapore": "Asia/Singapore",
  "hongkong": "Asia/Hong_Kong",
  "hong kong": "Asia/Hong_Kong",
  "seoul": "Asia/Seoul",
  "beijing": "Asia/Shanghai",
  "shanghai": "Asia/Shanghai",
  "bangkok": "Asia/Bangkok",
  "jakarta": "Asia/Jakarta",
  "manila": "Asia/Manila",
  "kuala": "Asia/Kuala_Lumpur",
  "taipei": "Asia/Taipei",
  "karachi": "Asia/Karachi",
  "dhaka": "Asia/Dhaka",
  "tehran": "Asia/Tehran",
  "jerusalem": "Asia/Jerusalem",
  "telaviv": "Asia/Jerusalem",
  "istanbul": "Europe/Istanbul",
  "cairo": "Africa/Cairo",
  "lagos": "Africa/Lagos",
  "nairobi": "Africa/Nairobi",
  "johannesburg": "Africa/Johannesburg",
  "capetown": "Africa/Johannesburg",
  "sydney": "Australia/Sydney",
  "melbourne": "Australia/Melbourne",
  "perth": "Australia/Perth",
  "auckland": "Pacific/Auckland",
  "honolulu": "Pacific/Honolulu",
  "anchorage": "America/Anchorage",
  "chicago": "America/Chicago",
  "denver": "America/Denver",
  "phoenix": "America/Phoenix",
  "toronto": "America/Toronto",
  "vancouver": "America/Vancouver",
  "mexicocity": "America/Mexico_City",
  "mexico city": "America/Mexico_City",
  "saopaulo": "America/Sao_Paulo",
  "sao paulo": "America/Sao_Paulo",
  "buenosaires": "America/Argentina/Buenos_Aires",
  "buenos aires": "America/Argentina/Buenos_Aires",
  "lima": "America/Lima",
  "bogota": "America/Bogota",
  "santiago": "America/Santiago",
  "honkong": "Asia/Hong_Kong",
  "andorra": "Europe/Andorra",
  "kabul": "Asia/Kabul",
  "tirane": "Europe/Tirane",
  "yerevan": "Asia/Yerevan",
  "casey": "Antarctica/Casey",
  "davis": "Antarctica/Davis",
  "mawson": "Antarctica/Mawson",
  "palmer": "Antarctica/Palmer",
  "rothera": "Antarctica/Rothera",
  "troll": "Antarctica/Troll",
  "vostok": "Antarctica/Vostok",
  "cordoba": "America/Argentina/Cordoba",
  "salta": "America/Argentina/Salta",
  "jujuy": "America/Argentina/Jujuy",
  "tucuman": "America/Argentina/Tucuman",
  "catamarca": "America/Argentina/Catamarca",
  "larioja": "America/Argentina/La_Rioja",
  "la rioja": "America/Argentina/La_Rioja",
  "sanjuan": "America/Argentina/San_Juan",
  "san juan": "America/Argentina/San_Juan",
  "mendoza": "America/Argentina/Mendoza",
  "sanluis": "America/Argentina/San_Luis",
  "san luis": "America/Argentina/San_Luis",
  "riogallegos": "America/Argentina/Rio_Gallegos",
  "rio gallegos": "America/Argentina/Rio_Gallegos",
  "ushuaia": "America/Argentina/Ushuaia",
  "pagopago": "Pacific/Pago_Pago",
  "pago pago": "Pacific/Pago_Pago",
  "lordhowe": "Australia/Lord_Howe",
  "lord howe": "Australia/Lord_Howe",
  "macquarie": "Antarctica/Macquarie",
  "hobart": "Australia/Hobart",
  "brokenhill": "Australia/Broken_Hill",
  "broken hill": "Australia/Broken_Hill",
  "brisbane": "Australia/Brisbane",
  "lindeman": "Australia/Lindeman",
  "adelaide": "Australia/Adelaide",
  "darwin": "Australia/Darwin",
  "eucla": "Australia/Eucla",
  "baku": "Asia/Baku",
  "barbados": "America/Barbados",
  "brussels": "Europe/Brussels",
  "sofia": "Europe/Sofia",
  "bermuda": "Atlantic/Bermuda",
  "lapaz": "America/La_Paz",
  "la paz": "America/La_Paz",
  "noronha": "America/Noronha",
  "belem": "America/Belem",
  "fortaleza": "America/Fortaleza",
  "recife": "America/Recife",
  "araguaina": "America/Araguaina",
  "maceio": "America/Maceio",
  "bahia": "America/Bahia",
  "campogrande": "America/Campo_Grande",
  "campo grande": "America/Campo_Grande",
  "cuiaba": "America/Cuiaba",
  "santarem": "America/Santarem",
  "portovelho": "America/Porto_Velho",
  "porto velho": "America/Porto_Velho",
  "boavista": "America/Boa_Vista",
  "boa vista": "America/Boa_Vista",
  "manaus": "America/Manaus",
  "eirunepe": "America/Eirunepe",
  "riobranco": "America/Rio_Branco",
  "rio branco": "America/Rio_Branco",
  "thimphu": "Asia/Thimphu",
  "minsk": "Europe/Minsk",
  "belize": "America/Belize",
  "stjohns": "America/St_Johns",
  "st johns": "America/St_Johns",
  "halifax": "America/Halifax",
  "glacebay": "America/Glace_Bay",
  "glace bay": "America/Glace_Bay",
  "moncton": "America/Moncton",
  "goosebay": "America/Goose_Bay",
  "goose bay": "America/Goose_Bay",
  "iqaluit": "America/Iqaluit",
  "winnipeg": "America/Winnipeg",
  "resolute": "America/Resolute",
  "rankininlet": "America/Rankin_Inlet",
  "rankin inlet": "America/Rankin_Inlet",
  "regina": "America/Regina",
  "swiftcurrent": "America/Swift_Current",
  "swift current": "America/Swift_Current",
  "edmonton": "America/Edmonton",
  "cambridgebay": "America/Cambridge_Bay",
  "cambridge bay": "America/Cambridge_Bay",
  "inuvik": "America/Inuvik",
  "dawsoncreek": "America/Dawson_Creek",
  "dawson creek": "America/Dawson_Creek",
  "fortnelson": "America/Fort_Nelson",
  "fort nelson": "America/Fort_Nelson",
  "whitehorse": "America/Whitehorse",
  "dawson": "America/Dawson",
  "zurich": "Europe/Zurich",
  "abidjan": "Africa/Abidjan",
  "rarotonga": "Pacific/Rarotonga",
  "coyhaique": "America/Coyhaique",
  "puntaarenas": "America/Punta_Arenas",
  "punta arenas": "America/Punta_Arenas",
  "easter": "Pacific/Easter",
  "urumqi": "Asia/Urumqi",
  "costarica": "America/Costa_Rica",
  "costa rica": "America/Costa_Rica",
  "havana": "America/Havana",
  "capeverde": "Atlantic/Cape_Verde",
  "cape verde": "Atlantic/Cape_Verde",
  "nicosia": "Asia/Nicosia",
  "famagusta": "Asia/Famagusta",
  "santodomingo": "America/Santo_Domingo",
  "santo domingo": "America/Santo_Domingo",
  "algiers": "Africa/Algiers",
  "guayaquil": "America/Guayaquil",
  "galapagos": "Pacific/Galapagos",
  "tallinn": "Europe/Tallinn",
  "elaaiun": "Africa/El_Aaiun",
  "el aaiun": "Africa/El_Aaiun",
  "ceuta": "Africa/Ceuta",
  "canary": "Atlantic/Canary",
  "helsinki": "Europe/Helsinki",
  "fiji": "Pacific/Fiji",
  "stanley": "Atlantic/Stanley",
  "kosrae": "Pacific/Kosrae",
  "faroe": "Atlantic/Faroe",
  "tbilisi": "Asia/Tbilisi",
  "cayenne": "America/Cayenne",
  "gibraltar": "Europe/Gibraltar",
  "nuuk": "America/Nuuk",
  "danmarkshavn": "America/Danmarkshavn",
  "scoresbysund": "America/Scoresbysund",
  "thule": "America/Thule",
  "athens": "Europe/Athens",
  "southgeorgia": "Atlantic/South_Georgia",
  "south georgia": "Atlantic/South_Georgia",
  "guatemala": "America/Guatemala",
  "guam": "Pacific/Guam",
  "bissau": "Africa/Bissau",
  "guyana": "America/Guyana",
  "tegucigalpa": "America/Tegucigalpa",
  "port-au-prince": "America/Port-au-Prince",
  "budapest": "Europe/Budapest",
  "pontianak": "Asia/Pontianak",
  "makassar": "Asia/Makassar",
  "jayapura": "Asia/Jayapura",
  "dublin": "Europe/Dublin",
  "chagos": "Indian/Chagos",
  "baghdad": "Asia/Baghdad",
  "jamaica": "America/Jamaica",
  "amman": "Asia/Amman",
  "bishkek": "Asia/Bishkek",
  "tarawa": "Pacific/Tarawa",
  "kanton": "Pacific/Kanton",
  "kiritimati": "Pacific/Kiritimati",
  "pyongyang": "Asia/Pyongyang",
  "almaty": "Asia/Almaty",
  "qyzylorda": "Asia/Qyzylorda",
  "qostanay": "Asia/Qostanay",
  "aqtobe": "Asia/Aqtobe",
  "aqtau": "Asia/Aqtau",
  "atyrau": "Asia/Atyrau",
  "oral": "Asia/Oral",
  "beirut": "Asia/Beirut",
  "colombo": "Asia/Colombo",
  "monrovia": "Africa/Monrovia",
  "vilnius": "Europe/Vilnius",
  "riga": "Europe/Riga",
  "tripoli": "Africa/Tripoli",
  "casablanca": "Africa/Casablanca",
  "chisinau": "Europe/Chisinau",
  "kwajalein": "Pacific/Kwajalein",
  "yangon": "Asia/Yangon",
  "ulaanbaatar": "Asia/Ulaanbaatar",
  "hovd": "Asia/Hovd",
  "macau": "Asia/Macau",
  "martinique": "America/Martinique",
  "malta": "Europe/Malta",
  "mauritius": "Indian/Mauritius",
  "maldives": "Indian/Maldives",
  "cancun": "America/Cancun",
  "merida": "America/Merida",
  "monterrey": "America/Monterrey",
  "matamoros": "America/Matamoros",
  "chihuahua": "America/Chihuahua",
  "ciudadjuarez": "America/Ciudad_Juarez",
  "ciudad juarez": "America/Ciudad_Juarez",
  "ojinaga": "America/Ojinaga",
  "mazatlan": "America/Mazatlan",
  "bahiabanderas": "America/Bahia_Banderas",
  "bahia banderas": "America/Bahia_Banderas",
  "hermosillo": "America/Hermosillo",
  "tijuana": "America/Tijuana",
  "kuching": "Asia/Kuching",
  "maputo": "Africa/Maputo",
  "windhoek": "Africa/Windhoek",
  "noumea": "Pacific/Noumea",
  "norfolk": "Pacific/Norfolk",
  "managua": "America/Managua",
  "kathmandu": "Asia/Kathmandu",
  "nauru": "Pacific/Nauru",
  "niue": "Pacific/Niue",
  "chatham": "Pacific/Chatham",
  "panama": "America/Panama",
  "tahiti": "Pacific/Tahiti",
  "marquesas": "Pacific/Marquesas",
  "gambier": "Pacific/Gambier",
  "portmoresby": "Pacific/Port_Moresby",
  "port moresby": "Pacific/Port_Moresby",
  "bougainville": "Pacific/Bougainville",
  "warsaw": "Europe/Warsaw",
  "miquelon": "America/Miquelon",
  "pitcairn": "Pacific/Pitcairn",
  "puertorico": "America/Puerto_Rico",
  "puerto rico": "America/Puerto_Rico",
  "gaza": "Asia/Gaza",
  "hebron": "Asia/Hebron",
  "lisbon": "Europe/Lisbon",
  "madeira": "Atlantic/Madeira",
  "azores": "Atlantic/Azores",
  "palau": "Pacific/Palau",
  "asuncion": "America/Asuncion",
  "qatar": "Asia/Qatar",
  "bucharest": "Europe/Bucharest",
  "belgrade": "Europe/Belgrade",
  "kaliningrad": "Europe/Kaliningrad",
  "simferopol": "Europe/Simferopol",
  "kirov": "Europe/Kirov",
  "volgograd": "Europe/Volgograd",
  "astrakhan": "Europe/Astrakhan",
  "saratov": "Europe/Saratov",
  "ulyanovsk": "Europe/Ulyanovsk",
  "samara": "Europe/Samara",
  "yekaterinburg": "Asia/Yekaterinburg",
  "omsk": "Asia/Omsk",
  "novosibirsk": "Asia/Novosibirsk",
  "barnaul": "Asia/Barnaul",
  "tomsk": "Asia/Tomsk",
  "novokuznetsk": "Asia/Novokuznetsk",
  "krasnoyarsk": "Asia/Krasnoyarsk",
  "irkutsk": "Asia/Irkutsk",
  "chita": "Asia/Chita",
  "yakutsk": "Asia/Yakutsk",
  "khandyga": "Asia/Khandyga",
  "vladivostok": "Asia/Vladivostok",
  "ust-nera": "Asia/Ust-Nera",
  "magadan": "Asia/Magadan",
  "sakhalin": "Asia/Sakhalin",
  "srednekolymsk": "Asia/Srednekolymsk",
  "kamchatka": "Asia/Kamchatka",
  "anadyr": "Asia/Anadyr",
  "riyadh": "Asia/Riyadh",
  "guadalcanal": "Pacific/Guadalcanal",
  "khartoum": "Africa/Khartoum",
  "paramaribo": "America/Paramaribo",
  "juba": "Africa/Juba",
  "saotome": "Africa/Sao_Tome",
  "sao tome": "Africa/Sao_Tome",
  "elsalvador": "America/El_Salvador",
  "el salvador": "America/El_Salvador",
  "damascus": "Asia/Damascus",
  "grandturk": "America/Grand_Turk",
  "grand turk": "America/Grand_Turk",
  "ndjamena": "Africa/Ndjamena",
  "dushanbe": "Asia/Dushanbe",
  "fakaofo": "Pacific/Fakaofo",
  "dili": "Asia/Dili",
  "ashgabat": "Asia/Ashgabat",
  "tunis": "Africa/Tunis",
  "tongatapu": "Pacific/Tongatapu",
  "kyiv": "Europe/Kyiv",
  "detroit": "America/Detroit",
  "louisville": "America/Kentucky/Louisville",
  "monticello": "America/Kentucky/Monticello",
  "indianapolis": "America/Indiana/Indianapolis",
  "vincennes": "America/Indiana/Vincennes",
  "winamac": "America/Indiana/Winamac",
  "marengo": "America/Indiana/Marengo",
  "petersburg": "America/Indiana/Petersburg",
  "vevay": "America/Indiana/Vevay",
  "tellcity": "America/Indiana/Tell_City",
  "tell city": "America/Indiana/Tell_City",
  "knox": "America/Indiana/Knox",
  "menominee": "America/Menominee",
  "center": "America/North_Dakota/Center",
  "newsalem": "America/North_Dakota/New_Salem",
  "new salem": "America/North_Dakota/New_Salem",
  "beulah": "America/North_Dakota/Beulah",
  "boise": "America/Boise",
  "losangeles": "America/Los_Angeles",
  "los angeles": "America/Los_Angeles",
  "juneau": "America/Juneau",
  "sitka": "America/Sitka",
  "metlakatla": "America/Metlakatla",
  "yakutat": "America/Yakutat",
  "nome": "America/Nome",
  "adak": "America/Adak",
  "montevideo": "America/Montevideo",
  "samarkand": "Asia/Samarkand",
  "tashkent": "Asia/Tashkent",
  "caracas": "America/Caracas",
  "hochiminh": "Asia/Ho_Chi_Minh",
  "ho chi minh": "Asia/Ho_Chi_Minh",
  "efate": "Pacific/Efate",
  "apia": "Pacific/Apia"
};
